"""add lobby tables

Revision ID: 96fc2f278240
Revises: 01a9d1dca7ac
Create Date: 2026-06-17 18:14:30.406732

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96fc2f278240'
down_revision: Union[str, Sequence[str], None] = '01a9d1dca7ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lobbies',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('code', sa.String(length=8), nullable=False),
    sa.Column('creator_id', sa.String(), nullable=False),
    sa.Column('mode', sa.Enum('casual', 'ranked', name='lobby_mode_enum'), nullable=False),
    sa.Column('difficulty', sa.Enum('easy', 'medium', 'hard', name='lobby_difficulty_enum'), nullable=False),
    sa.Column('status', sa.Enum('waiting', 'active', name='lobby_status_enum'), nullable=False),
    sa.Column('match_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('lobby_members',
    sa.Column('lobby_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['lobby_id'], ['lobbies.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('lobby_id', 'user_id')
    )
    op.add_column('match_participants', sa.Column('board_state', sa.JSON(), nullable=False, server_default='[]'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('match_participants', 'board_state')
    op.drop_table('lobby_members')
    op.drop_table('lobbies')
    # ### end Alembic commands ###
